version: '3.9'

services:
  db:
    image: jitesoft/sqlite:latest
    volumes:
      - ./backend/database.db:/var/lib/sqlite/data.db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
